### ISSUE TITLE
Issue with shutdownRequest and new release of enchannel-zmq-backend

### ISSUE THREAD

**Issue by awright415** [nteract/enchannel#22]
I was testing out some of ntereact's lower-level libraries in a project and noticed shutdownRequest has an implicit dependency on the filter operator that's causing issues.

After the recent PRs in nteract (https://github.com/nteract/nteract/pull/1780) and enchannel-zmq-backend (https://github.com/nteract/enchannel-zmq-backend/pull/55) pared down the imported operators, there's no longer a guarantee that the shell channel has the filter operator.

A simple `import "rxjs/add/operator/filter";` resolves the problem.

**Comment by rgbkrk** [comment]
Oooh thanks for noting. We'll want to update that here too.

**Comment by rgbkrk** [comment]
Just updated and shipped enchannel `v2.0.0`, though I'm hoping we'd move this into `@nteract/messaging`.
